name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set-executable
      run: chmod +x ./build.sh
    - name: addpkgs
      run: sudo apt-get install lld clang
    - name: build
      run: ./build.sh wasm32; # ./build.sh wasm64
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git push origin HEAD:v$(cat ./version)

