name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set-executable
      run: chmod +x ./build.sh
    - name: addpkgs
      run: sudo apt-get install lld clang
    - name: build
      run: chmod +x *.sh; ./build.sh wasm32; ./update_ver.sh; export VERSION=$(cat version) # ./build.sh wasm64
    - name: push
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        title: "WCLibC ${{ env.VERSION }}"
        files: wclibc-*
